# LM_ONLY

# General
use_wandb: True 
debug: False 
run_name: roberta_large_CET
experiment_model: lm_only
pretrain_model: roberta-large
dataset: qasc
input_format: each_option
is_CET: True
CET_topk: 5
CET_weight: 0.9

# Training
n_epochs: 8
max_epochs_before_stop: 10
unfreeze_epoch: 0 
accumulate_batch_size: 128
batch_size: 8
eval_batch_size: 8
inhouse: True
lr: 1e-5 
optim: radam 